---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

- name: Set compose version
  ansible.builtin.set_fact:
    docker_compose_version: "{{ wado_compose_version }}"
  when: wado_compose_version is defined

- name: Install Docker
  ansible.builtin.include_role:
    name: nmusatti.docker_ce

- name: Create the docker user with userid 1000
  ansible.builtin.user:
    name: "{{ waco_docker_user }}"
    group: docker
    # password: '*'
    # update_password: on_create
    uid: 1000
  ignore_errors: true
  register: docker_user
  become: true

- name: Create the docker user with a different userid
  ansible.builtin.user:
    name: "{{ waco_docker_user }}"
    group: docker
    state: present
    password: '*'
    update_password: on_create
  become: true
  when: docker_user is failed
