---
# Workstation as Code
# Copyright Nicola Musatti 2022.

- name: Install Dropox flatpak (RedHat)
  include_tasks:
    file: flatpak.yml
  vars:
    flatpak_remote: flathub
    flatpak_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    flatpak_method: system
    flatpak_apps:
      - com.dropbox.Client
  when: ansible_os_family == 'RedHat' and waco_flatpak_apps | length > 0

# - name: Install Dropbox repository (Ubuntu)
#   include_tasks:
#     file: apt_repo.yml
#   vars:
#     apt_repo_filename: dropbox
#     apt_key_url: https://linux.dropbox.com/ubuntu
#     apt_key_server: pgp.mit.edu
#     apt_key_id: 1C61A2656FB57B7E4DE0F4C1FC918B335044912E
#     apt_repo_definition: "deb [arch={{ dpkg_architecture.stdout }}] https://linux.dropbox.com/ubuntu {{ lsb_release.stdout }} main"

- name: "Install Dropbox"
  apt:
    name:
      - nautilus-dropbox
  become: true
  when: waco_platform == 'Ubuntu'
