---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: Install flatpak (EL 8, Fedora)
  dnf:
    name: flatpak
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: Install system packages (EL 7)
  yum:
    name: flatpak
  become: true
  when: waco_platform == 'EL7'

- name: Add a flatpak repository remote
  community.general.flatpak_remote:
    name: "{{ flatpak_remote }}"
    state: present
    flatpakrepo_url: "{{ flatpak_url }}"
    method: "{{ flatpak_method }}"
  become: true
  become_user: "{{ ( flatpak_method == 'system' ) | ternary('root', flatpak_user) }}"

- name: Install flatpaks from a remote
  community.general.flatpak:
    name: "{{ flatpak_app }}"
    state: present
    remote: "{{ flatpak_remote }}"
    method: "{{ flatpak_method }}"
  become: true
  become_user: "{{ ( flatpak_method == 'system' ) | ternary('root', flatpak_user) }}"
  loop: "{{ flatpak_apps }}"
  loop_control:
    loop_var: flatpak_app
