---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: Check whether the nmusatti/grsync repository is enabled
  command: dnf copr list --enabled
  register: grsync_enabled
  check_mode: false
  ignore_errors: true
  changed_when: false
  when: waco_platform == 'CentOS8'

- name: Enable the nmusatti/grsync repository
  command: dnf copr -y enable nmusatti/grsync
  become: true
  when: waco_platform == 'CentOS8' and grsync_enabled.stdout.find('nmusatti/grsync') == -1

- name: Install grsync (CentOS8, Fedora)
  dnf:
    name:
      - grsync
    state: present
  become: true
  when: waco_platform in ( 'CentOS8', 'Fedora' )

- name: Install grsync (CentOS7)
  yum:
    name:
      - grsync
    state: present
  become: true
  when: waco_platform == 'CentOS7'
