---
# Workstation as Code
# Copyright Nicola Musatti 2021.

- name: "Install the required packages (EL 8, Fedora)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - yum-utils
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: "Install the required packages (EL 7)"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - yum-utils
  become: true
  when: waco_platform == 'EL7'

- name: Check if the official HashiCorp repository is available (RedHat)
  stat:
    path: /etc/yum.repos.d/hashicorp.repo
  register: packer_repo
  when: ansible_os_family == 'RedHat'

- name: Install the official HashiCorp repository (RedHat)
  command: "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/{{ waco_hashi_distro }}/hashicorp.repo"
  become: true
  when: ansible_os_family == 'RedHat' and packer_repo.stat.exists is defined and not packer_repo.stat.exists

- name: Install the required packages (Ubuntu)
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Check if the official Hashicorp apt repository is available (Ubuntu)
  stat:
    path: /etc/apt/sources.list.d/hashicorp.list
  register: hashicorp_repo
  when: ansible_distribution == 'Ubuntu'

- name: Install the official Hashicorp GPG key (Ubuntu)
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
  when: ansible_distribution == 'Ubuntu' and hashicorp_repo.stat.exists is defined and not hashicorp_repo.stat.exists

- name: Retrieve package architecture
  command: "dpkg --print-architecture"
  register: dpkg_architecture
  when: ansible_distribution == 'Ubuntu' and hashicorp_repo.stat.exists is defined and not hashicorp_repo.stat.exists

- name: Retrieve LSB release (Ubuntu)
  command: "lsb_release -cs"
  register: lsb_release
  when: ansible_distribution == 'Ubuntu' and hashicorp_repo.stat.exists is defined and not hashicorp_repo.stat.exists

- name: Install the official Hashicorp repository (Ubuntu)
  apt_repository:
    repo: "deb [arch={{ dpkg_architecture.stdout }}] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"
    filename: hashicorp
  become: true
  when: ansible_distribution == 'Ubuntu' and hashicorp_repo.stat.exists is defined and not hashicorp_repo.stat.exists
