---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: Install Docker
  include_tasks:
    file: docker.yml
  when: waco_has_docker

- name: Install Python
  include_role:
    name: waco-python
  when: waco_has_python

- name: Install MATE
  include_role:
    name: waco-mate
  when: waco_has_mate

- name: Install system packages (CentOS 8, Fedora)
  dnf:
    name: "{{ packages }}"
  vars:
    packages: "{{ waco_packages }}"
  become: true
  when: waco_platform == 'CentOS8' or waco_platform == 'Fedora'

- name: Install system packages (CentOS 7)
  yum:
    name: "{{ packages }}"
  vars:
    packages: "{{ waco_packages }}"
  become: true
  when: waco_platform == 'CentOS7'

- name: Install system-wide flatpak apps
  include_tasks:
    file: flatpak.yml
  vars:
    flatpak_remote: flathub
    flatpak_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    flatpak_method: system
    flatpak_apps: "{{ waco_flatpak_apps }}"
  when: waco_flatpak_apps | length > 0
