---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: Install Docker
  include_role:
    name: nmusatti.docker_ce
  when: waco_has_docker

- name: Install Python
  include_role:
    name: waco-python
  when: waco_has_python

- name: Install MATE
  include_role:
    name: waco-mate
  when: waco_has_mate
