---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2021.

- name: Install deltarpm support (EL 8, Fedora)
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - drpm
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: Install deltarpm support (EL 7)
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - deltarpm
  become: true
  when: waco_platform in ( 'EL7' )

- name: Enable the EPEL repository (EL 8, EL 7)
  include_role:
    name: geerlingguy.repo-epel
  when: waco_platform in ( 'EL8', 'EL7' )

- name: Enable the PowerTools repository (EL 8)
  include_tasks:
    file: powertools.yml
  when: waco_platform == 'EL8'

- name: Install Docker
  include_tasks:
    file: docker.yml
  when: waco_has_docker

- name: Install Python
  include_role:
    name: waco-python
  when: waco_has_python

- name: Install system packages (EL 8, Fedora)
  dnf:
    name: "{{ packages }}"
  vars:
    packages: "{{ waco_packages }}"
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: Install system packages (EL 7)
  yum:
    name: "{{ packages }}"
  vars:
    packages: "{{ waco_packages }}"
  become: true
  when: waco_platform == 'EL7'

- name: Install system-wide flatpak apps
  include_tasks:
    file: flatpak.yml
  vars:
    flatpak_remote: flathub
    flatpak_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    flatpak_method: system
    flatpak_apps: "{{ waco_flatpak_apps }}"
  when: waco_flatpak_apps | length > 0

- name: Install grsync
  include_tasks:
    file: grsync.yml
  vars:
  when: waco_has_grsync

- name: Install Maven
  include_tasks:
    file: maven.yml
  vars:
  when: waco_has_maven

- name: Install Packer
  include_tasks:
    file: packer.yml
  vars:
  when: waco_has_packer

- name: Install Vagrant
  include_tasks:
    file: vagrant.yml
  vars:
  when: waco_has_vagrant

- name: Install VirtualBox
  include_tasks:
    file: virtualbox.yml
  vars:
  when: waco_has_virtualbox

- name: Install Visual Studio Code
  include_tasks:
    file: vscode.yml
  vars:
  when: waco_has_vscode

- name: Install user specific components
  include_tasks:
    file: user.yml
  vars:
    user: "{{ item }}"
    dict: "{{ waco_user_settings[item] | default(waco_user_defaults) }}"
    user_has_rust: "{{ dict['has_rust'] | default(waco_user_defaults['has_rust']) }}"
    user_flatpak_apps: "{{ dict['flatpak_apps'] | default(waco_user_defaults['flatpak_apps']) }}"
  loop: "{{ waco_users }}"
