---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2025.

- name: Install system packages for Maven (EL10, EL 9, EL 8, Fedora)
  ansible.builtin.dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - unzip
  become: true
  when: waco_platform in ('EL10', 'EL9', 'EL8', 'Fedora')

- name: Install system packages for Maven (Ubuntu)
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - unzip
  become: true
  when: waco_platform == 'Ubuntu'

- name: "Create base directories for Maven"
  ansible.builtin.file:
    dest: "{{ item }}"
    state: directory
    mode: 0755
  become: true
  loop:
    - "{{ waco_install_dir }}"
    - "{{ waco_software_dir }}"
    - "{{ waco_software_dir }}/maven"

- name: Download the Maven archive
  ansible.builtin.get_url:
    dest: "{{ waco_software_dir }}/maven"
    url: "https://archive.apache.org/dist/maven/maven-3/{{ wamvn_version }}/binaries/apache-maven-{{ wamvn_version }}-bin.zip"
    mode: 0644
  become: true
  retries: 3
  delay: 3

- name: Unpack the Maven archive
  ansible.builtin.unarchive:
    src: "{{ waco_software_dir }}/maven/apache-maven-{{ wamvn_version }}-bin.zip"
    dest: "/opt"
    mode: 0755
    remote_src: true
  become: true
