---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

- name: "Install Packer (EL 9, EL 8, Fedora)"
  ansible.builtin.dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - packer
  become: true
  when: waco_platform in ('EL9', 'EL8', 'Fedora')
  register: packer_installed

- name: "Install Packer (EL 7)"
  ansible.builtin.yum:
    name: "{{ packages }}"
  vars:
    packages:
      - packer
  become: true
  when: waco_platform == 'EL7'
  register: packer_installed

# - name: Disable the official Hashicorp repository (RedHat)
#   command: "yum-config-manager --disable hashicorp.repo"
#   become: true
#   when: ansible_os_family == 'RedHat' and packer_installed is changed and wapa_disable_repo

- name: "Install Packer (Ubuntu)"
  ansible.builtin.apt:
    name:
      - packer
  become: true
  when: ansible_distribution == 'Ubuntu'
  register: packer_installed

# - name: Remove the official Hashicorp repository (Ubuntu)
#   apt_repository:
#     repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"
#     file: hashicorp
#     present: false
#   become: true
#   when: ansible_distribution == 'Ubuntu' and packer_installed is changed and wapa_disable_repo
