---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: "Install the required packages (EL 8, Fedora)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - yum-utils
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: "Install the required packages (EL 7)"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - yum-utils
  become: true
  when: waco_platform == 'EL7'

- name: Check if the official HashiCorp repository is available
  stat:
    path: /etc/yum.repos.d/hashicorp.repo
  register: packer_repo

- name: Install the official Packer repository
  command: "yum-config-manager --add-repo https://rpm.releases.hashicorp.com/{{ waco_hashi_distro }}/hashicorp.repo"
  become: true
  when: packer_repo.stat.exists is defined and not packer_repo.stat.exists

- name: "Install Packer (EL 8, Fedora)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - packer
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )
  register: packer_installed

- name: "Install Packer (EL 7)"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - packer
  become: true
  when: waco_platform == 'EL7'
  register: packer_installed

- name: Disable the official Packer repository
  command: "yum-config-manager --disable packer.repo"
  become: true
  when: packer_installed is changed and wapa_disable_repo
