---
# Workstation as Code
# Copyright Nicola Musatti 2020.

# CentOS 8 only

- name: Check whether the PowerTools repository is enabled
  command: grep -q 'enabled=1' /etc/yum.repos.d/CentOS-PowerTools.repo
  register: powertools_enabled
  check_mode: false
  ignore_errors: true
  changed_when: false

- name: Install DNF plugins
  dnf:
    name:
      - dnf-plugins-core
    state: present
  become: true
  when: powertools_enabled.rc != 0

- name: Enable the PowerTools repository
  command: dnf config-manager --set-enabled PowerTools
  become: true
  when: powertools_enabled.rc != 0
