---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

# EL 8 only

- name: Check whether the PowerTools repository is enabled
  ansible.builtin.command: "grep -q 'enabled=1' /etc/yum.repos.d/{{ waco_powertools_file }}"
  register: powertools_enabled
  check_mode: false
  ignore_errors: true
  changed_when: false

- name: Install DNF plugins
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
    state: present
  become: true
  when: powertools_enabled.rc != 0

- name: Enable the PowerTools repository
  ansible.builtin.command: "dnf config-manager --set-enabled {{ waco_powertools_name }}"
  become: true
  when: powertools_enabled.rc != 0
