---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

- name: Download the Rust installation script
  ansible.builtin.get_url:
    dest: "/tmp/rustup.sh"
    url: "https://sh.rustup.rs"
    mode: 0755
  become: true
  retries: 3
  delay: 3

- name: Execute the Rust installation script
  ansible.builtin.command:
    cmd: "/bin/sh /tmp/rustup.sh -y"
    creates: "/home/{{ user }}/.cargo/bin/rustup"
  become: true
  become_user: "{{ user }}"
