---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: "Create the {{ user }} user"
  user:
    name: "{{ user }}"
    state: present
    password: '*'
  become: true

- name: "Install user flatpak apps for user {{ user }}"
  include_tasks:
    file: flatpak.yml
  vars:
    flatpak_remote: flathub
    flatpak_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    flatpak_method: user
    flatpak_apps: "{{ user_flatpak_apps }}"
    flatpak_user: "{{ user }}"
    allow_world_readable_tmpfiles: true
  when: user_flatpak_apps | length > 0

- name: "Install Rust for user {{ user }}"
  include_tasks:
    file: rust.yml
  vars:
  when: user_has_rust
