---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2023.

- name: "Create user {{ user }}"
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
    password: '*'
    update_password: on_create
  become: true

- name: "Install user flatpak apps for user {{ user }}"
  ansible.builtin.include_tasks:
    file: flatpak.yml
  vars:
    flatpak_remote: flathub
    flatpak_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
    flatpak_method: user
    flatpak_apps: "{{ user_flatpak_apps }}"
    flatpak_user: "{{ user }}"
    allow_world_readable_tmpfiles: true
  when: ansible_os_family == 'RedHat' and user_flatpak_apps | length > 0

- name: "Install Rust for user {{ user }}"
  ansible.builtin.include_tasks:
    file: rust.yml
  when: user_has_rust
