---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2021.

- name: "Install Vagrant (EL 8, Fedora)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - vagrant
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )
  register: vagrant_installed

- name: "Install Vagrant (EL 7)"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - vagrant
  become: true
  when: waco_platform == 'EL7'
  register: vagrant_installed

- name: "Install Vagrant (Ubuntu)"
  apt:
    name:
      - vagrant
  become: true
  when: ansible_distribution == 'Ubuntu'
  register: vagrant_installed
