---
# Workstation as Code
# Copyright Nicola Musatti 2020.

- name: Create base directories for Vagrant
  file:
    dest: "{{ item }}"
    state: directory
    mode: 0755
  become: true
  loop:
    - "{{ waco_software_dir }}"
    - "{{ waco_software_dir }}/vagrant"

- name: Download the Vagrant package
  get_url:
    dest: "{{ waco_software_dir }}/vagrant"
    url: "https://releases.hashicorp.com/vagrant/{{ wava_version }}/vagrant_{{ wava_version }}_x86_64.rpm"
    mode: 0644
  become: true
  retries: 3
  delay: 3

- name: "Install Vagrant (EL 8, Fedora)"
  dnf:
    name: "{{ waco_software_dir }}/vagrant/vagrant_{{ wava_version }}_x86_64.rpm"
    disable_gpg_check: true
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: "Install Vagrant (EL 7)"
  yum:
    name: "{{ waco_software_dir }}/vagrant/vagrant_{{ wava_version }}_x86_64.rpm"
  become: true
  when: waco_platform == 'EL7'
