---
# Workstation as Code
# Copyright Nicola Musatti 2020 - 2022.

- name: Check if the official VS Code repository is available
  stat:
    path: /etc/yum.repos.d/vscode.repo
  register: vscode_repo
  when: ansible_os_family == 'RedHat'

- name: Copy the VS Code repo file
  copy:
    src: vscode.repo
    dest: /tmp
    mode: 0644
    owner: root
    group: root
  become: true
  register: vscode_file
  when: ansible_os_family == 'RedHat' and vscode_repo.stat.exists is defined and not vscode_repo.stat.exists

- name: Install the official VS Code repository
  command: "yum-config-manager --add-repo /tmp/vscode.repo"
  become: true
  when: ansible_os_family == 'RedHat' and vscode_file is changed

- name: "Install VS Code (EL 8, Fedora)"
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - code
  become: true
  when: waco_platform in ( 'EL8', 'Fedora' )

- name: "Install VS Code (EL 7)"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - code
  become: true
  when: waco_platform == 'EL7'

- name: Install the required packages (Ubuntu)
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Check if the official VS Code apt repository is available (Ubuntu)
  stat:
    path: /etc/apt/sources.list.d/vscode.list
  register: vscode_repo
  when: ansible_distribution == 'Ubuntu'

- name: Install the official VS Code GPG key (Ubuntu)
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/packages.microsoft.gpg
    state: present
  when: ansible_distribution == 'Ubuntu' and vscode_repo.stat.exists is defined and not vscode_repo.stat.exists

- name: Retrieve package architecture
  command: "dpkg --print-architecture"
  register: dpkg_architecture
  when: ansible_distribution == 'Ubuntu' and vscode_repo.stat.exists is defined and not vscode_repo.stat.exists

- name: Retrieve LSB release (Ubuntu)
  command: "lsb_release -cs"
  register: lsb_release
  when: ansible_distribution == 'Ubuntu' and vscode_repo.stat.exists is defined and not vscode_repo.stat.exists

- name: Install the official VS Code repository (Ubuntu)
  apt_repository:
    repo: "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
  become: true
  when: ansible_distribution == 'Ubuntu' and vscode_repo.stat.exists is defined and not vscode_repo.stat.exists

- name: "Install VS Code (Ubuntu)"
  apt:
    name:
      - code
  become: true
  when: waco_platform == 'Ubuntu'
