---
- name: Converge
  hosts: all
  environment:
    DOCKER_HOST: unix:///docker.sock
  tasks:
    - name: "Include waco-master"
      include_role:
        name: "waco-master"
      vars:
        waco_packages:
          - vim-X11
        waco_flatpak_apps:
          - org.musicbrainz.Picard
        waco_has_docker: true
        wado_compose_version: 1.26.2
        waco_has_grsync: true
        waco_has_maven: true
        wamvn_version: 3.5.4
        waco_has_packer: true
        waco_has_python: true
        wapy_source_versions:
          - 3.7.9
          - 2.7.18
        waco_has_vagrant: true
        waco_has_virtualbox: true
        wavb_el_package: "6.1.14_140239_el{{ ansible_distribution_major_version }}-1"
        wavb_package: "{{ ( waco_platform == 'Fedora' ) | ternary('', wavb_el_package) }}"
        waco_has_vscode: true
        waco_users: [ "user" ]
        waco_user_settings:
          user:
            has_rust: true
            flatpak_apps:
              - io.github.quodlibet.QuodLibet
