---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: centos7
    image: nmusatti/centos7-pys-systemd
    command: /sbin/init
    pre_build_image: true
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: centos8
    image: nmusatti/centos8-pys-systemd
    command: /sbin/init
    pre_build_image: true
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: fedora
    image: nmusatti/fedora-pys-systemd
    command: /sbin/init
    pre_build_image: true
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
