---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: $TOX_ENVNAME
    image: nmusatti/${TOX_ENVNAME}-pys-systemd
    command: /sbin/init
    pre_build_image: true
    privileged: True
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: testinfra
  directory: ../resources/tests/docker
