---
- name: Converge
  hosts: all
  tasks:
    - name: "Include waco-master"
      include_role:
        name: "waco-master"
      vars:
        waco_has_python: true
        wapy_source_versions:
          - 3.7.9
          - 2.7.18
