---
- name: Converge
  hosts: all
  roles:
    - role: waco_org.waco_master
  vars:
    waco_has_dropbox: true
    waco_has_grsync: true
    waco_has_maven: true
    wamvn_version: 3.8.4
    waco_has_packer: true
    waco_has_vagrant: true
    waco_has_virtualbox: true
    #wavb_el_package: "6.1.14_140239_el{{ ansible_distribution_major_version }}-1"
    #wavb_package: "{{ ( waco_platform == 'Fedora' ) | ternary('', wavb_el_package) }}"
    waco_has_vscode: true
    waco_users: [ "user" ]
    waco_user_settings:
      user:
        has_rust: true
