---
- name: Converge
  hosts: all
  tasks:
    - name: "Include waco-master"
      include_role:
        name: "waco-master"
      vars:
        waco_has_grsync: true
        waco_has_maven: true
        wamvn_version: 3.5.4
        waco_has_virtualbox: true
        wavb_el_package: "6.1.14_140239_el{{ ansible_distribution_major_version }}-1"
        wavb_package: "{{ ( waco_platform == 'Fedora' ) | ternary('', wavb_el_package) }}"
        waco_has_vscode: true
        waco_users: [ "user" ]
        waco_user_settings:
          user:
            has_rust: true
